### ISSUE TITLE
Blog - issue with Logo on Firefox

### ISSUE THREAD

**Issue by danivovich** [smartlogic/smartlogic.github.com#115]
Blog has a Logo issue on Firefox
![screen shot 2015-02-05 at 7 25 36 am](https://cloud.githubusercontent.com/assets/122999/6060262/244df5ec-ad09-11e4-8d96-2cb05185160a.png)

Looks like the sprite is not aligned correctly.

**Comment by yflicker** [comment]
should be fixed
