### ISSUE TITLE
Mobile view - SmartLogic text moves overtop of content

### ISSUE THREAD

**Issue by danivovich** [smartlogic/smartlogic.github.com#116]
When in the mobile breakpoint, when scrolling down, the smartlogic brand text on the left side follows the page, which is nice on tablet size, but on mobile it goes over top of other content because there isn't enough gutter.
![screen shot 2015-02-05 at 7 27 01 am](https://cloud.githubusercontent.com/assets/122999/6060271/3f9ac320-ad09-11e4-9604-5e943fb7d778.png)

**Comment by yflicker** [comment]
@ryandestefano bumping this

**Comment by danivovich** [comment]
fixed by #128
