### ISSUE TITLE
Add CTA code to OrderUp case study

### ISSUE THREAD

**Issue by yflicker** [smartlogic/smartlogic.github.com#118]
<span class="hs-cta-wrapper" id="hs-cta-wrapper-b6ebef09-7c45-4c5d-8c24-df4387c4d8b8"> <span class="hs-cta-node hs-cta-b6ebef09-7c45-4c5d-8c24-df4387c4d8b8" id="hs-cta-b6ebef09-7c45-4c5d-8c24-df4387c4d8b8"> 
   <a href="http://cta-redirect.hubspot.com/cta/redirect/451063/b6ebef09-7c45-4c5d-8c24-df4387c4d8b8" target="_blank"><img class="hs-cta-img" id="hs-cta-img-b6ebef09-7c45-4c5d-8c24-df4387c4d8b8" style="border-width:0px;" src="//no-cache.hubspot.com/cta/default/451063/b6ebef09-7c45-4c5d-8c24-df4387c4d8b8.png" alt="Have Lunch With SmartLogic"></a> </span> <script charset="utf-8" src="//js.hscta.net/cta/current.js"></script> <script type="text/javascript">
        hbspt.cta.load(451063, 'b6ebef09-7c45-4c5d-8c24-df4387c4d8b8');
    </script> </span>

**Comment by yflicker** [comment]
@leannematlach is this perhaps something we want to try across the board on all of our case studies?

**Comment by leannematlach** [comment]
@yflicker yes. I remember us talking about it a while ago and then never doing anything.
