### ISSUE TITLE
The hamburger doesn't work on Chrome on iPhone 6S

### ISSUE THREAD

**Issue by yflicker** [smartlogic/smartlogic.github.com#126]
See below. The hamburger slides out but nothing appears inside.

![image1](https://cloud.githubusercontent.com/assets/16272/10261300/19561af8-695f-11e5-873c-cadb6fe51a87.PNG)

**Comment by mattmenefee** [comment]
Doesn't work on the 5s either in chrome

**Comment by mattmenefee** [comment]
Also, the team member pictures do weird things when you attempt to scroll over them in chrome on a touchscreen. I can explain what I mean by this better if you reach out to me.

**Comment by yflicker** [comment]
Yeah, it needs to detect a scroll differently than a tap. @ryandestefano what's your workload like? Can you fix the hamburger?

**Comment by ryandestefano** [comment]
I got the menu opening and closing again, not sure how to get rid of the highlight that appears on the hamburger button when you tap it. Mobile Chrome doesn't seem to be accepting user-select/outline/tap-highlight rules.

**Comment by danivovich** [comment]
All but the highlight fixed by #127
